In [1]:
import cv2
import numpy as np

In [2]:
canvas = np.zeros((512,512,3), dtype=np.uint8) # Tuvalimizi oluşturuyoruz, bu fonksiyon belli bir alanı siyah tuval oluşturur ama biz bunu parametreler ile beyaz yapacağız.
print(canvas)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


* **Görüldüğü gibi sıfırlardan oluşan bir matris ortaya çıkıyor**

In [3]:
cv2.imshow("canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# Şimdi tuvali beyaz yapalım yani matris değerimizin tümü 255 olması lazım.

canvas = np.zeros((512,512,3), dtype=np.uint8) + 255  # + 255 eklersek matrisdeki tüm değerlere 255 ekliyoruz.
print(canvas)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [5]:
cv2.imshow("canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()